V4 develop
jooby-dev/jooby-rest-server pull request #11
Opened 2024-06-18 22:10 UTC by Pnom

2024-06-19 07:48 UTC, DarkPark commented on src/constants/protocols.js
>  export const MTX = 'mtx';
```suggestion
export const MTX1 = 'mtx1';
```

should we switch to this?

2024-06-19 07:54 UTC, DarkPark commented on src/utils/getBytesFromString.js
> +const getBytesFromString = ( bytes, bytesConversionFormats = HEX ) => (bytesConversionFormats === HEX
```suggestion
const getBytesFromString = ( bytes, bytesConversionFormats = HEX ) => (
    bytesConversionFormats === HEX
```
?

2024-06-19 07:55 UTC, DarkPark commented on src/utils/getStringFromBytes.js
> +    bytesConversionFormat === BASE64 ? getBase64FromBytes(bytes) : getHexFromBytes(bytes)
```suggestion
    bytesConversionFormat === BASE64
        ? getBase64FromBytes(bytes) : getHexFromBytes(bytes)
```

?

2024-06-19 10:56 UTC, DeadByElpy requested changes

2024-06-19 10:56 UTC, DeadByElpy commented on readme.md
>  | `POST` | `/v1/decoder`              | General decoder route. Requires to specify [protocol](#protocols) in the requests body.  |
```suggestion
| `POST` | `/v2/decoder`              | General decoder route. Requires to specify [protocol](#protocols) in the requests body.  |
```

and others

2024-06-19 11:20 UTC, DarkPark commented on src/routes/v2/index.js
> +    //chirpstack(fastify);
why disable?

2024-06-19 15:18 UTC, Pnom commented on src/constants/protocols.js
>  export const MTX = 'mtx';
use names same as in jooby-codec

2024-06-19 15:18 UTC, Pnom commented on src/utils/getBytesFromString.js
> +const getBytesFromString = ( bytes, bytesConversionFormats = HEX ) => (bytesConversionFormats === HEX
fixed

2024-06-19 15:19 UTC, Pnom commented on src/utils/getStringFromBytes.js
> +    bytesConversionFormat === BASE64 ? getBase64FromBytes(bytes) : getHexFromBytes(bytes)
fixed

2024-06-19 15:19 UTC, Pnom commented on src/routes/v2/index.js
> +    //chirpstack(fastify);
fixed

2024-06-19 16:36 UTC, Pnom commented on readme.md
>  | `POST` | `/v1/decoder`              | General decoder route. Requires to specify [protocol](#protocols) in the requests body.  |
fixed

2024-06-19 16:40 UTC, DeadByElpy approved these changes

2024-06-20 09:05 UTC, DarkPark commented on src/utils/getStringFromBytes.js
> +        ? getBase64FromBytes(bytes) : getHexFromBytes(bytes)
```suggestion
        ? getBase64FromBytes(bytes)
        : getHexFromBytes(bytes)
```

2024-06-20 09:05 UTC, DarkPark commented on src/utils/getBytesFromString.js
> +        ? getBytesFromHex(bytes) : getBytesFromBase64(bytes)
```suggestion
        ? getBytesFromHex(bytes)
        : getBytesFromBase64(bytes)
```

2024-06-20 09:12 UTC, Pnom commented on src/utils/getBytesFromString.js
> +        ? getBytesFromHex(bytes) : getBytesFromBase64(bytes)
fixed

2024-06-20 09:12 UTC, Pnom commented on src/utils/getStringFromBytes.js
> +        ? getBase64FromBytes(bytes) : getHexFromBytes(bytes)
fixed

2024-06-20 09:20 UTC, DarkPark approved these changes

2024-06-20 09:21 UTC, merged