add encoders
jooby-dev/jooby-rest-server pull request #4
Opened 2024-03-04 16:09 UTC by Pnom

2024-03-05 10:15 UTC, DarkPark commented
for a commit comment it's better to use `:` to separate topic from message, for example
instead of `controllers/decoders. add common utils` use `controllers/decoders: add common utils`

2024-03-05 11:57 UTC, DarkPark requested changes

2024-03-05 11:57 UTC, DarkPark commented on src/routes/v1/utils/validateDecoderRequest.js
> +export const validateDecoderRequest = ( {body}, reply, done ) => {
how about `requestDecoder.js` and export function `validate`?

or even `request.js` and keep here everything related

2024-03-05 11:57 UTC, DarkPark commented on package.json
> +        "api:build": "redocly bundle ./api/openapi.yaml",
`        "api:bundle": "redocly bundle ./api/openapi.yaml",`
?

2024-03-05 11:57 UTC, DarkPark commented on src/routes/v1/utils/validateGeneralRequest.js
> +import {validateDecoderRequest, validateEncoderRequest} from './validateRequest.js';
![image](https://github.com/jooby-dev/jooby-rest-server/assets/1189578/b701469f-83f8-479c-bf5a-83f16e41fe9c)

it should be ok to remove `validate` from each file name and use them for any related helpers

2024-03-05 11:57 UTC, DarkPark commented on src/routes/v1/utils/validateMtxAesParameters.js
> +const validateAesParameters = ( request, reply ) => {
`export const validateMtxAesDecoderParameters = ( request, reply ) => {`

?

2024-03-05 11:57 UTC, DarkPark commented on src/routes/v1/utils/validateMtxRequest.js
> +    const {
in such simple cases it's better to put it in a single line

2024-03-05 11:57 UTC, DarkPark commented on src/controllers/utils/prepareCommands.js
> +import {utils} from 'jooby-codec/index.js';
`src/controllers/utils/preparations.js` ? or something

as there is not only single prepareCommands inside

2024-03-05 11:57 UTC, DarkPark commented on src/controllers/utils/prepareCommands.js
> +    return json ? {id, name, ...JSON.parse(json)} : {id, name};
can `json` be an empty string? a `"null"` string? an empty object `"{}"` string?

maybe firstly create `let result = {id, name};` and then extend it with parsed json in try/catch without conditional checks?

2024-03-05 11:57 UTC, DarkPark commented on src/controllers/decoders/mtxLora.js
> +    const {
imo still can be in one line

2024-03-05 11:57 UTC, DarkPark commented on src/controllers/decoders/obisObserver.js
> +        framingFormat,
not `frameFormat`?

2024-03-05 11:57 UTC, DarkPark commented on src/controllers/decoders/obisObserver.js
> +            ? {frames: decodeFrames(body, 7).map(frame => decodeFrame(frame, body))}
would be nice to have some constant for 7 and 8

2024-03-05 11:57 UTC, DarkPark commented on src/controllers/decoders/obisObserver.js
> +            protocol: 'obisObserver',
constants for protocols are also welcomed

2024-03-05 11:57 UTC, DarkPark commented on tests/analogDecoderTest.js
> +import fastify from '../src/index.js';
do we need word `Test` in `analogDecoderTest.js`? each file here is a test

2024-03-05 11:57 UTC, DarkPark commented on tests/analogDecoderTest.js
> +    for ( let index = 0; index < tests.length; index++ ) {
it possible to simplify a little here with `tests.forEach`

2024-03-05 11:57 UTC, DarkPark commented on tests/analogDecoderTest.js
> +    for ( let index = 0; index < tests.length; index++ ) {
also create individual `it` for each `tests` object

2024-03-05 11:57 UTC, DarkPark commented on tests/analogSegmentsDecoder1Test.js
> +const testUrl = async ( url, request = {} ) => {
can we move this function to utils?

2024-03-05 11:57 UTC, DarkPark commented on tests/obisObserverEncoderTest.js
> +import post from './utils/postRequest.js';
`import postRequest from './utils/postRequest.js';`

or

`import post from './utils/post.js';`

2024-03-05 11:57 UTC, DarkPark commented on tests/utils/postRequest.js
> +                    'Content-Type': 'application/json'
there is a way to do it for each request - https://axios-http.com/docs/config_defaults

2024-03-06 07:26 UTC, Pnom commented on package.json
> +        "api:build": "redocly bundle ./api/openapi.yaml",
fixed

2024-03-06 07:28 UTC, Pnom commented on src/routes/v1/utils/validateMtxRequest.js
> +    const {
fixed

2024-03-06 07:28 UTC, Pnom commented on tests/analogDecoderTest.js
> +    for ( let index = 0; index < tests.length; index++ ) {
fixed

2024-03-06 07:28 UTC, Pnom commented on tests/analogSegmentsDecoder1Test.js
> +const testUrl = async ( url, request = {} ) => {
fixed

2024-03-06 07:28 UTC, Pnom commented on tests/obisObserverEncoderTest.js
> +import post from './utils/postRequest.js';
fixed

2024-03-06 07:28 UTC, Pnom commented on tests/utils/postRequest.js
> +                    'Content-Type': 'application/json'
fixed

2024-03-06 08:00 UTC, Pnom commented on src/routes/v1/utils/validateDecoderRequest.js
> +export const validateDecoderRequest = ( {body}, reply, done ) => {
fixed

2024-03-06 08:00 UTC, Pnom commented on src/routes/v1/utils/validateGeneralRequest.js
> +import {validateDecoderRequest, validateEncoderRequest} from './validateRequest.js';
fixed

2024-03-06 09:32 UTC, DarkPark commented on tests/utils/postRequest.js
> +        return await axios.post(
better in a single line

2024-03-06 09:33 UTC, DarkPark commented on tests/obisObserverEncoderTest.js
> +const routs = [
```suggestion
const routes = [
```
?

2024-03-06 09:34 UTC, DarkPark commented on tests/utils/runTestsSequence.js
> +        routs.forEach( route => runRouteTest(route, tests));
```suggestion
        routs.forEach(route => runRouteTest(route, tests));
```

2024-03-06 11:40 UTC, Pnom commented on tests/obisObserverEncoderTest.js
> +const routs = [
fixed

2024-03-06 11:41 UTC, Pnom commented on tests/utils/runTestsSequence.js
> +        routs.forEach( route => runRouteTest(route, tests));
fixed

2024-03-06 11:42 UTC, Pnom commented on tests/utils/postRequest.js
> +        return await axios.post(
fixed

2024-03-06 11:42 UTC, Pnom commented on src/controllers/decoders/obisObserver.js
> +        framingFormat,
framingFormat is ok

2024-03-06 11:42 UTC, Pnom commented on src/controllers/decoders/mtxLora.js
> +    const {
fixed

2024-03-06 11:48 UTC, Pnom commented on src/controllers/utils/prepareCommands.js
> +import {utils} from 'jooby-codec/index.js';
fixed

2024-03-06 11:54 UTC, Pnom commented on src/controllers/utils/prepareCommands.js
> +    return json ? {id, name, ...JSON.parse(json)} : {id, name};
fixed

2024-03-06 12:09 UTC, Pnom commented on src/controllers/decoders/obisObserver.js
> +            protocol: 'obisObserver',
fixed

2024-03-06 12:12 UTC, Pnom commented on src/controllers/decoders/obisObserver.js
> +            ? {frames: decodeFrames(body, 7).map(frame => decodeFrame(frame, body))}
fixed

2024-03-06 14:36 UTC, DarkPark commented on src/constants/protocols.js
> +export const analog = 'analog';
```suggestion
export const ANALOG = 'analog'; 
```
?

2024-03-06 14:41 UTC, closed without merging

2024-03-06 14:41 UTC, Pnom commented on src/constants/protocols.js
> +export const analog = 'analog';
fixed